name: Publish PR Commit Pkg

on:
  push:
    branches:
      - main
    tags:
      - '!**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jaderd-jh/vite-plugin-debugger' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g corepack@latest --force | corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpx pkg-pr-new publish --pnpm './packages/*'
